import type { Usuario, Partido, Prediccion } from "../types";

// USUARIOS DE EJEMPLO
export const usuariosMock: Usuario[] = [
  {
    id: "1",
    name: "Biwash Shrestha",
    nombre: "Biwash Shrestha",
    email: "biwash@goalz.com",
    password: "password123",
    role: "admin",
    totalPoints: 245,
    puntosTotal: 245,
    correctPredictions: 12,
    totalPredictions: 25,
  },
  {
    id: "2",
    name: "Carlos Gol",
    nombre: "Carlos Gol",
    email: "carlos@goalz.com",
    password: "password123",
    role: "user",
    totalPoints: 230,
    puntosTotal: 230,
    correctPredictions: 11,
    totalPredictions: 24,
  },
  {
    id: "3",
    name: "Ana Portera",
    nombre: "Ana Portera",
    email: "ana@goalz.com",
    password: "password123",
    role: "user",
    totalPoints: 260,
    puntosTotal: 260,
    correctPredictions: 13,
    totalPredictions: 23,
  },
  {
    id: "4",
    name: "Luis Delantero",
    nombre: "Luis Delantero",
    email: "luis@goalz.com",
    password: "password123",
    role: "user",
    totalPoints: 215,
    puntosTotal: 215,
    correctPredictions: 10,
    totalPredictions: 26,
  },
  {
    id: "5",
    name: "María Defensa",
    nombre: "María Defensa",
    email: "maria@goalz.com",
    password: "password123",
    role: "user",
    totalPoints: 200,
    puntosTotal: 200,
    correctPredictions: 9,
    totalPredictions: 22,
  },
];

// PARTIDOS DE EJEMPLO
export const partidosMock: Partido[] = [
  {
    id: "1",
    homeTeam: "Real Madrid",
    equipoLocal: "Real Madrid",
    awayTeam: "FC Barcelona",
    equipoVisitante: "FC Barcelona",
    date: "2024-04-21T21:00:00.000Z",
    fecha: "2024-04-21T21:00:00.000Z",
    matchday: 32,
    status: "pending",
    estado: "pendiente",
    result: null,
    resultado: null,
  },
  {
    id: "2",
    homeTeam: "Manchester City",
    equipoLocal: "Manchester City",
    awayTeam: "Arsenal",
    equipoVisitante: "Arsenal",
    date: "2024-03-31T17:30:00.000Z",
    fecha: "2024-03-31T17:30:00.000Z",
    matchday: 30,
    status: "finished",
    estado: "finalizado",
    result: {
      homeGoals: 0,
      awayGoals: 0,
      golesLocal: 0,
      golesVisitante: 0,
    },
    resultado: {
      homeGoals: 0,
      awayGoals: 0,
      golesLocal: 0,
      golesVisitante: 0,
    },
  },
  {
    id: "3",
    homeTeam: "Atlético Madrid",
    equipoLocal: "Atlético Madrid",
    awayTeam: "Girona",
    equipoVisitante: "Girona",
    date: "2024-04-13T14:00:00.000Z",
    fecha: "2024-04-13T14:00:00.000Z",
    matchday: 31,
    status: "pending",
    estado: "pendiente",
    result: null,
    resultado: null,
  },
  {
    id: "4",
    homeTeam: "PSG",
    equipoLocal: "PSG",
    awayTeam: "Dortmund",
    equipoVisitante: "Dortmund",
    date: "2024-05-07T21:00:00.000Z",
    fecha: "2024-05-07T21:00:00.000Z",
    matchday: 33,
    status: "pending",
    estado: "pendiente",
    result: null,
    resultado: null,
  },
  {
    id: "5",
    homeTeam: "Bayern Munich",
    equipoLocal: "Bayern Munich",
    awayTeam: "Real Madrid",
    equipoVisitante: "Real Madrid",
    date: "2024-05-01T21:00:00.000Z",
    fecha: "2024-05-01T21:00:00.000Z",
    matchday: 32,
    status: "finished",
    estado: "finalizado",
    result: {
      homeGoals: 2,
      awayGoals: 2,
      golesLocal: 2,
      golesVisitante: 2,
    },
    resultado: {
      homeGoals: 2,
      awayGoals: 2,
      golesLocal: 2,
      golesVisitante: 2,
    },
  },
];

// PREDICCIONES DE EJEMPLO
export const prediccionesMock: Prediccion[] = [
  {
    id: "1",
    matchId: "2",
    idPartido: "2",
    userId: "1",
    idUsuario: "1",
    prediction: "1",
    prediccion: "1",
    exactScore: {
      home: 2,
      away: 1,
      local: 2,
      visitante: 1,
    },
    marcadorExacto: {
      home: 2,
      away: 1,
      local: 2,
      visitante: 1,
    },
    points: 0,
    puntosGanados: 0,
    createdAt: "2024-03-30T10:00:00.000Z",
  },
  {
    id: "2",
    matchId: "5",
    idPartido: "5",
    userId: "1",
    idUsuario: "1",
    prediction: "X",
    prediccion: "X",
    exactScore: {
      home: 2,
      away: 2,
      local: 2,
      visitante: 2,
    },
    marcadorExacto: {
      home: 2,
      away: 2,
      local: 2,
      visitante: 2,
    },
    points: 5,
    puntosGanados: 5,
    createdAt: "2024-04-30T10:00:00.000Z",
  },
];
